var getCache = require('./lru_cache');

// var c = getCache(5);
// c.put('a', 'a');
// c.put('b2', 'b');
// c.put('c2', 'c');
// c.put('d4', 'd');
// c.put('e4', 'e');
// console.log('\ngetting a', c.get('a'));
// console.log('\ngetting e', c.get('e'));
// console.log('\ngetting c', c.get('c'));
// // put('f', 6);
// c.del('a');
// c.del('e');
// c.put('f', 'f');
// c.put('g', 'g');
// c.get('d');
// c.put('h', 'h');

var d = getCache(5);
d.put('a', 'a');
// console.log(d.length());
console.log('list',d.list());
console.log();
d.put('b', 'b');
console.log('list',d.list());
console.log();
// console.log(d.length());
d.put('c', 'c');
console.log('list',d.list());
console.log();
d.put('d', 'd');
d.put('e', 'e');
console.log('\ngetting a', d.get('a'));
console.log('\ngetting e', d.get('e'));
console.log('\ngetting c', d.get('c'));
// put('f', 6);
// console.log(d.length());
console.log('deleting a');
d.del('a');
// console.log(d.length());
console.log('list');
console.log('list',d.list());
console.log();
d.del('e');
// d.del('e');
d.put('f', 'f', 3);
d.put('g', 'g');
console.log('key d:',d.get('d'));
d.put('h', 'h', 4);
console.log(d.list());
console.log('deleted lru',d.delLru());
// console.log(c.list());
console.log('list',d.list());
console.log();
console.log(d.stats());
